services:
  lego_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'teste'
      POSTGRES_DB: 'teste'
      POSTGRES_PASSWORD: '123456'
    ports:
      - "5432:5432"

  lego_app:
    image: lego_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - lego_database
    environment:
      DATABASE_URL: postgresql+psycopg://teste:teste@lego_database:5432/teste

volumes:
  pgdata: